version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pelisres
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"  
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./backend/Pelisres
    container_name: springboot_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: pelisres
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./frontend/pelisres
    container_name: nextjs_app
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://springboot_app:8080
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
